/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi_Kasir;

/**
 *
 * @author Alex
 */
public class HistoryTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form HistoryTransaksi
     */
    public HistoryTransaksi() {
        initComponents();

        jTable.setModel(TableMethods.getQueryModel(
                """
             SELECT p.id_pembayaran, ti.kode, b.nama, b.harga, ti.jumlah, p.total_harga, p.waktu, p.status
             FROM `pembayaran` p
             LEFT OUTER JOIN transaksi_items ti ON p.id_pembayaran = ti.id_pembayaran
             LEFT OUTER JOIN barang b ON ti.kode = b.kode;
             """
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transaction_type = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        allRadio = new javax.swing.JRadioButton();
        makananRadio = new javax.swing.JRadioButton();
        pulsaRadio = new javax.swing.JRadioButton();
        tokenRadio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        fieldSearch = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("History");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Jenis Transaksi");

        transaction_type.add(allRadio);
        allRadio.setSelected(true);
        allRadio.setText("All Transactions");
        allRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRadioActionPerformed(evt);
            }
        });

        transaction_type.add(makananRadio);
        makananRadio.setText("Makanan/Barang");

        transaction_type.add(pulsaRadio);
        pulsaRadio.setText("Pulsa");
        pulsaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsaRadioActionPerformed(evt);
            }
        });

        transaction_type.add(tokenRadio);
        tokenRadio.setText("Token");
        tokenRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenRadioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Find Payment (ID)");

        btnFind.setText("View");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(allRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pulsaRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(makananRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tokenRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFind)
                                .addGap(18, 18, 18)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allRadio)
                    .addComponent(makananRadio)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsaRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tokenRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Home frame = new Home();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void allRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allRadioActionPerformed

    private void pulsaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsaRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulsaRadioActionPerformed

    private void tokenRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokenRadioActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String sql = "";

        if (tokenRadio.isSelected()) {
            sql = """
                  SELECT p.id_pembayaran, h.no_meteran, h.token, p.total_harga, p.waktu, p.status
                  FROM pembayaran p
                    LEFT OUTER JOIN transaksi_items t ON p.id_pembayaran = t.id_pembayaran
                    RIGHT OUTER JOIN token_history h ON t.kode = h.kode
                  """;
        } else if (makananRadio.isSelected()) {
            sql = """
                    SELECT p.id_pembayaran, b.kode, b.nama, b.harga, t.jumlah, p.total_harga, p.waktu, p.status FROM pembayaran p
                        LEFT OUTER JOIN transaksi_items t ON t.id_pembayaran = p.id_pembayaran
                        LEFT OUTER JOIN barang b  ON t.kode = b.kode
                        LEFT OUTER JOIN makanan m ON t.kode = m.kode
                        LEFT OUTER JOIN pulsa_history pi ON t.kode = pi.kode
                        LEFT OUTER JOIN token_history th on t.kode = th.kode
                    WHERE th.id_pembayaran IS NULL AND pi.id_pembayaran IS NULL;
                  """;
        } else if (pulsaRadio.isSelected()) {
            sql = """
                  SELECT p.id_pembayaran, h.operator, h.no_telp, p.total_harga, p.waktu, p.status
                  FROM pembayaran p
                    LEFT OUTER JOIN transaksi_items t ON p.id_pembayaran = t.id_pembayaran
                    RIGHT OUTER JOIN pulsa_history h ON t.kode = h.kode
                  """;
        } else {
            sql
                    = """
             SELECT p.id_pembayaran, ti.kode, b.nama, b.harga, ti.jumlah, p.total_harga, p.waktu, p.status
             FROM `pembayaran` p
                LEFT OUTER JOIN transaksi_items ti ON p.id_pembayaran = ti.id_pembayaran
                LEFT OUTER JOIN barang b ON ti.kode = b.kode
             """;
        }

        if (fieldSearch.getText().length() > 0) {
            if (makananRadio.isSelected()) {
                sql += " AND p.id_pembayaran = '" + fieldSearch.getText() + "'";
            } else {
                sql += " WHERE p.id_pembayaran = '" + fieldSearch.getText() + "'";
            }
        }

        sql += ";";

        TableMethods.updateTableModel(jTable, TableMethods.getQueryModel(sql));
        fieldSearch.setText("");


    }//GEN-LAST:event_btnFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allRadio;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFind;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JRadioButton makananRadio;
    private javax.swing.JRadioButton pulsaRadio;
    private javax.swing.JRadioButton tokenRadio;
    private javax.swing.ButtonGroup transaction_type;
    // End of variables declaration//GEN-END:variables

}
