/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi_Kasir;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author Alex
 */
public class KasirPulsa extends javax.swing.JFrame {

    /**
     * Creates new form KasirPulsa
     */
    public KasirPulsa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleksi_pulsa = new javax.swing.ButtonGroup();
        seleksi_pembayaran = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldNoTelp = new javax.swing.JTextField();
        fieldOperator = new javax.swing.JTextField();
        btnKonfirmasi = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        radioPulsa10 = new javax.swing.JRadioButton();
        radioPulsa50 = new javax.swing.JRadioButton();
        radioPulsa100 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kasRadio = new javax.swing.JRadioButton();
        debitRadio = new javax.swing.JRadioButton();
        qrisRadio = new javax.swing.JRadioButton();
        exitBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Isi Pulsa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("No HP");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Operator");

        btnKonfirmasi.setText("Konfirmasi");
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        seleksi_pulsa.add(radioPulsa10);
        radioPulsa10.setText("10.000");

        seleksi_pulsa.add(radioPulsa50);
        radioPulsa50.setText("50.000");

        seleksi_pulsa.add(radioPulsa100);
        radioPulsa100.setText("100.000");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setText("Jumlah Pulsa");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Metode Pembayaran");

        seleksi_pembayaran.add(kasRadio);
        kasRadio.setText("Cash");

        seleksi_pembayaran.add(debitRadio);
        debitRadio.setText("Debit");

        seleksi_pembayaran.add(qrisRadio);
        qrisRadio.setText("QRIS");

        exitBtn1.setText("Back");
        exitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKonfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNoTelp)
                            .addComponent(fieldOperator)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioPulsa10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioPulsa50, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioPulsa100, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kasRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(debitRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(qrisRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBtn1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(exitBtn1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldOperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPulsa10)
                    .addComponent(radioPulsa50)
                    .addComponent(radioPulsa100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kasRadio)
                    .addComponent(debitRadio)
                    .addComponent(qrisRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        if (!checkString(fieldNoTelp.getText(), 10, 12)){
            JOptionPane.showMessageDialog(null, "Nomor HP tidak sesuai! Panjang harus diantara 10 - 12 angka, sekarang sebanyak " + fieldNoTelp.getText().length() + " angka dan tidak boleh diisi huruf/simbol.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (seleksi_pulsa.getSelection() == null || seleksi_pembayaran.getSelection() == null){
            JOptionPane.showMessageDialog(null, "Tolong pilih jumlah pulsa dan/atau metode pembayaran!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Pulsa temppulsa = createPulsa();
        MetodePembayaran new_payment;
        
        if (kasRadio.isSelected()) {
            new_payment = new Kas(temppulsa.getHarga());
        } else if (debitRadio.isSelected()) {
            new_payment = new KartuDebit(temppulsa.getHarga());
        } else {
            new_payment = new QRIS(temppulsa.getHarga());
        }
        
        new_payment.addItem(temppulsa, 1);
        new_payment.setFlag(MetodePembayaran.Flags.PULSA);
        new_payment.Payment();
        
        fieldNoTelp.setText("");
        fieldOperator.setText("");
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        Home frame = new Home();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void exitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtn1ActionPerformed
        Home frame = new Home();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirPulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirPulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirPulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirPulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirPulsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JRadioButton debitRadio;
    private javax.swing.JButton exitBtn1;
    private javax.swing.JTextField fieldNoTelp;
    private javax.swing.JTextField fieldOperator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton kasRadio;
    private javax.swing.JRadioButton qrisRadio;
    private javax.swing.JRadioButton radioPulsa10;
    private javax.swing.JRadioButton radioPulsa100;
    private javax.swing.JRadioButton radioPulsa50;
    private javax.swing.ButtonGroup seleksi_pembayaran;
    private javax.swing.ButtonGroup seleksi_pulsa;
    // End of variables declaration//GEN-END:variables
    private boolean checkString(String input, int lengthmin, int lengthmax) {
        if (input == null || (input.length() < lengthmin || input.length() > lengthmax)) {
            return false;
        }

        for (char c : input.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }
    
    private Pulsa createPulsa(){
        String noTelp = fieldNoTelp.getText();
        String operator = fieldOperator.getText();
        float nominal = 0f;
        
        String kode = "";
        String nama = "";
        float harga = 0f;
        
        String sql = """
                     SELECT b.kode, b.nama, b.harga, p.nominal FROM barang b
                     INNER JOIN pulsa p ON p.kode = b.kode
                     WHERE p.kode = ?;
                     """;
        try {
            PreparedStatement stmt = DBConnector.conn.prepareStatement(sql);
            if (radioPulsa10.isSelected()){
                stmt.setString(1, "0008");
            }
            else if (radioPulsa50.isSelected()){
                stmt.setString(1, "0009");
            }
            else {
                stmt.setString(1, "0010");
            }
            
            ResultSet rs = stmt.executeQuery();
            if (rs.next()){
                nominal = rs.getFloat("nominal");
                kode = rs.getString("kode");
                nama = rs.getString("nama");
                harga = rs.getFloat("harga");
            }
        }
        catch (SQLException e){
            e.printStackTrace();
        }
        
        Pulsa temp = new Pulsa(operator,noTelp, nominal);
        temp.setKode(kode);
        temp.setHarga(harga);
        temp.setNama(nama);
        
        return temp;
    }
}
