package Aplikasi_Kasir;

import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class KasPayment extends javax.swing.JFrame {
    Kas payment_info;
    
    public KasPayment(){
        initComponents();
    }
    
    public KasPayment(Kas info_kas) {
        initComponents();
        payment_info = info_kas;
        fieldTotal.setText(Float.toString(info_kas.getTotalHarga()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitle = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelDibayar = new javax.swing.JLabel();
        fieldTotal = new javax.swing.JTextField();
        fieldDibayar = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelTitle.setText("Pembayaran Kas");

        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotal.setText("Total");

        labelDibayar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDibayar.setText("Uang Dibayar");

        fieldTotal.setEditable(false);
        fieldTotal.setText("total harga");

        fieldDibayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDibayarActionPerformed(evt);
            }
        });

        btnBayar.setText("Bayar");
        btnBayar.setActionCommand("doBayarKas");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnCancel.setText("Batal Pembayaran");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDibayar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldDibayar, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDibayar)
                    .addComponent(fieldDibayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void fieldDibayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDibayarActionPerformed
        doPayment();
    }//GEN-LAST:event_fieldDibayarActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        doPayment();
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTextField fieldDibayar;
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JLabel labelDibayar;
    private javax.swing.JLabel labelTotal;
    // End of variables declaration//GEN-END:variables

    //methods
    private boolean hasNonDigits(String str) {
        for (char ch : str.toCharArray()) {
            if (!Character.isDigit(ch)) {
                return true;
            }
        }
        return false;
    }
    
    private void doPayment(){
        if (hasNonDigits(fieldDibayar.getText())){
            fieldDibayar.setText("");
            JOptionPane.showMessageDialog(null, "Salah mengisi field 'Uang Dibayar', mohon dicek lagi!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
        else {
            payment_info.setDibayar(Float.parseFloat(fieldDibayar.getText()));
            payment_info.calculateChange();
            if (payment_info.getKembalian() >= 0){
                JOptionPane.showMessageDialog(null, "Pembayaran berhasil dilakukan!\nKembalian sebanyak " + payment_info.getKembalian(), "Successful Payment", JOptionPane.INFORMATION_MESSAGE);
                payment_info.setStatus(MetodePembayaran.PaymentState.SUCCESSFUL);
                DatabaseInsertion.insertNewPayment(payment_info);
                dispose();
            }
            else {
                JOptionPane.showMessageDialog(null, "Pembayaran gagal, jumlah yang dibayar tidak cukup!", "Unsuccessful Payment", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
}
